n1 = input ('digite algo: ')
print('é numerico?', (n1. isalnum()))
print('é alfanumerico?', (n1.isalnum()))
print('é minusculo?', (n1.islower()))
print('é maiuscula?', (n1.isupper()))
print('só tem espaços?', (n1.isspace()))
print('tem como imprimir?', (n1.isprintable()))